export{default as Homepage}from './Homepage'
export{default as Recruiterdata}from './RecruiterDataspage'
export{default as Login}from './Loginpage'
export{default as RecruiterProfile}from './Recruiterprofilepage'
export{default as Userprofile}from './Userprofilepage'
export{default as RecruiterJobs}from './Joblistingpage'